import { db } from './database';

// Exercise IDs — fixed so progression chains work
const EX = {
  gobletSquat:          'ex-001',
  barbellBackSquat:     'ex-002',
  bulgarianSplitSquat:  'ex-003',
  barbellFrontSquat:    'ex-004',
  pushUp:               'ex-005',
  dbBenchPress:         'ex-006',
  barbellBenchPress:    'ex-007',
  overheadDbPress:      'ex-008',
  barbellOhp:           'ex-009',
  weightedDip:          'ex-010',
  dbRdl:                'ex-011',
  barbellRdl:           'ex-012',
  conventionalDeadlift: 'ex-013',
  trapBarDeadlift:      'ex-014',
  dbRow:                'ex-015',
  latPulldown:          'ex-016',
  assistedChinUp:       'ex-017',
  bwChinUp:             'ex-018',
  weightedChinUp:       'ex-019',
  bwPullUp:             'ex-020',
  weightedPullUp:       'ex-021',
  cableRow:             'ex-022',
  dbBicepCurl:          'ex-023',
  barbellCurl:          'ex-024',
  hammerCurl:           'ex-025',
  overheadTricepExt:    'ex-026',
  tricepPushdown:       'ex-027',
  dbLateralRaise:       'ex-028',
  cableLateralRaise:    'ex-029',
  facePull:             'ex-030',
  plank:                'ex-031',
  deadBug:              'ex-032',
  farmersWalk:          'ex-033',
  abWheelRollout:       'ex-034',
};

const exercises = [
  // === SQUAT ===
  { id: EX.gobletSquat, name: 'Goblet Squat', movement_pattern: 'squat',
    muscle_groups: ['quads','glutes','upper_back','core'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 8, default_rep_max: 12, default_rest_sec: 120, is_compound: true,
    notes: 'Hold dumbbell at chest. Full depth, keep torso upright. Drive knees out.' },
  { id: EX.barbellBackSquat, name: 'Barbell Back Squat', movement_pattern: 'squat',
    muscle_groups: ['quads','glutes','spinal_erectors'], variation_level: 2,
    parent_exercise_id: EX.gobletSquat, is_bodyweight: false,
    default_rep_min: 5, default_rep_max: 8, default_rest_sec: 180, is_compound: true,
    notes: 'Bar on upper traps. Full depth below parallel. 3RIR on working sets.' },
  { id: EX.bulgarianSplitSquat, name: 'Bulgarian Split Squat', movement_pattern: 'squat',
    muscle_groups: ['quads','glutes','hip_flexors'], variation_level: 2,
    parent_exercise_id: EX.gobletSquat, is_bodyweight: false,
    default_rep_min: 8, default_rep_max: 10, default_rest_sec: 120, is_compound: true,
    notes: 'Rear foot elevated. Front shin vertical. Full depth.' },
  { id: EX.barbellFrontSquat, name: 'Barbell Front Squat', movement_pattern: 'squat',
    muscle_groups: ['quads','glutes','upper_back'], variation_level: 3,
    parent_exercise_id: EX.barbellBackSquat, is_bodyweight: false,
    default_rep_min: 4, default_rep_max: 6, default_rest_sec: 180, is_compound: true,
    notes: 'Bar on front delts. Elbows high throughout. Very upright torso.' },

  // === PRESS ===
  { id: EX.pushUp, name: 'Push-up', movement_pattern: 'press',
    muscle_groups: ['chest','anterior_deltoid','triceps'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: true,
    default_rep_min: 8, default_rep_max: 20, default_rest_sec: 90, is_compound: true,
    notes: 'Chest to floor. Full lockout. Body rigid. Can go to failure on bodyweight.' },
  { id: EX.dbBenchPress, name: 'Dumbbell Bench Press', movement_pattern: 'press',
    muscle_groups: ['chest','anterior_deltoid','triceps'], variation_level: 2,
    parent_exercise_id: EX.pushUp, is_bodyweight: false,
    default_rep_min: 8, default_rep_max: 12, default_rest_sec: 120, is_compound: true,
    notes: 'Full stretch at bottom. Explosive concentric. 3RIR on working sets.' },
  { id: EX.barbellBenchPress, name: 'Barbell Bench Press', movement_pattern: 'press',
    muscle_groups: ['chest','anterior_deltoid','triceps'], variation_level: 2,
    parent_exercise_id: EX.dbBenchPress, is_bodyweight: false,
    default_rep_min: 5, default_rep_max: 8, default_rest_sec: 180, is_compound: true,
    notes: 'Bar to sternum. Retract scapula. Leg drive. 3RIR.' },
  { id: EX.overheadDbPress, name: 'Overhead Dumbbell Press', movement_pattern: 'press',
    muscle_groups: ['deltoid','triceps','upper_traps'], variation_level: 2,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 8, default_rep_max: 12, default_rest_sec: 120, is_compound: true,
    notes: 'Neutral spine. Full lockout overhead. Control the descent.' },
  { id: EX.barbellOhp, name: 'Barbell Overhead Press', movement_pattern: 'press',
    muscle_groups: ['deltoid','triceps','upper_traps'], variation_level: 3,
    parent_exercise_id: EX.overheadDbPress, is_bodyweight: false,
    default_rep_min: 5, default_rep_max: 8, default_rest_sec: 180, is_compound: true,
    notes: 'Bar at clavicle start. Push bar over head, not in front. 3RIR.' },
  { id: EX.weightedDip, name: 'Weighted Dip', movement_pattern: 'press',
    muscle_groups: ['chest','triceps','anterior_deltoid'], variation_level: 3,
    parent_exercise_id: EX.barbellBenchPress, is_bodyweight: false,
    default_rep_min: 6, default_rep_max: 10, default_rest_sec: 180, is_compound: true,
    notes: 'Lean forward for chest emphasis. Full depth at bottom. 3RIR.' },

  // === HINGE ===
  { id: EX.dbRdl, name: 'Dumbbell Romanian Deadlift', movement_pattern: 'hinge',
    muscle_groups: ['hamstrings','glutes','spinal_erectors'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 8, default_rep_max: 10, default_rest_sec: 120, is_compound: true,
    notes: 'Hinge at hips. Keep back flat. Feel hamstring stretch. DBs stay close to legs.' },
  { id: EX.barbellRdl, name: 'Barbell Romanian Deadlift', movement_pattern: 'hinge',
    muscle_groups: ['hamstrings','glutes','spinal_erectors'], variation_level: 2,
    parent_exercise_id: EX.dbRdl, is_bodyweight: false,
    default_rep_min: 6, default_rep_max: 8, default_rest_sec: 180, is_compound: true,
    notes: 'Bar stays over mid-foot. Maintain neutral spine throughout. 3RIR.' },
  { id: EX.conventionalDeadlift, name: 'Conventional Deadlift', movement_pattern: 'hinge',
    muscle_groups: ['hamstrings','glutes','spinal_erectors','lats'], variation_level: 2,
    parent_exercise_id: EX.dbRdl, is_bodyweight: false,
    default_rep_min: 4, default_rep_max: 6, default_rest_sec: 240, is_compound: true,
    notes: 'Lats tight, chest up, drive floor away. Do not round lower back. 3RIR.' },
  { id: EX.trapBarDeadlift, name: 'Trap Bar Deadlift', movement_pattern: 'hinge',
    muscle_groups: ['hamstrings','glutes','spinal_erectors','quads'], variation_level: 2,
    parent_exercise_id: EX.dbRdl, is_bodyweight: false,
    default_rep_min: 5, default_rep_max: 8, default_rest_sec: 240, is_compound: true,
    notes: 'More quad-dominant than conventional. Safer for beginners. 3RIR.' },

  // === PULL ===
  { id: EX.dbRow, name: 'Dumbbell Row', movement_pattern: 'pull',
    muscle_groups: ['lats','rhomboids','mid_traps','biceps'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 10, default_rep_max: 12, default_rest_sec: 90, is_compound: true,
    notes: 'Brace on bench. Elbow to hip, not straight up. Full stretch at bottom.' },
  { id: EX.latPulldown, name: 'Lat Pulldown', movement_pattern: 'pull',
    muscle_groups: ['lats','biceps','rear_deltoid'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 10, default_rep_max: 12, default_rest_sec: 90, is_compound: true,
    notes: 'Lean slightly back. Pull bar to upper chest. Squeeze lats at bottom.' },
  { id: EX.assistedChinUp, name: 'Assisted Chin-up', movement_pattern: 'pull',
    muscle_groups: ['lats','biceps'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: true,
    default_rep_min: 8, default_rep_max: 12, default_rest_sec: 90, is_compound: true,
    notes: 'Use band or machine assistance. Underhand grip. Full dead hang at bottom.' },
  { id: EX.bwChinUp, name: 'Bodyweight Chin-up', movement_pattern: 'pull',
    muscle_groups: ['lats','biceps','rear_deltoid'], variation_level: 2,
    parent_exercise_id: EX.latPulldown, is_bodyweight: true,
    default_rep_min: 5, default_rep_max: 12, default_rest_sec: 120, is_compound: true,
    notes: 'Underhand grip. Dead hang start. Chin clearly over bar. Can go to failure.' },
  { id: EX.weightedChinUp, name: 'Weighted Chin-up', movement_pattern: 'pull',
    muscle_groups: ['lats','biceps','rear_deltoid'], variation_level: 3,
    parent_exercise_id: EX.bwChinUp, is_bodyweight: false,
    default_rep_min: 5, default_rep_max: 8, default_rest_sec: 180, is_compound: true,
    notes: 'Belt with plate or dumbbell between legs. 3RIR. Full ROM.' },
  { id: EX.bwPullUp, name: 'Bodyweight Pull-up', movement_pattern: 'pull',
    muscle_groups: ['lats','rear_deltoid','biceps'], variation_level: 2,
    parent_exercise_id: EX.latPulldown, is_bodyweight: true,
    default_rep_min: 5, default_rep_max: 12, default_rest_sec: 120, is_compound: true,
    notes: 'Overhand grip. Dead hang start. Chin over bar. Harder than chin-up for most.' },
  { id: EX.weightedPullUp, name: 'Weighted Pull-up', movement_pattern: 'pull',
    muscle_groups: ['lats','rear_deltoid','biceps'], variation_level: 3,
    parent_exercise_id: EX.bwPullUp, is_bodyweight: false,
    default_rep_min: 5, default_rep_max: 8, default_rest_sec: 180, is_compound: true,
    notes: 'Belt with plate. Full ROM. 3RIR.' },
  { id: EX.cableRow, name: 'Cable Row', movement_pattern: 'pull',
    muscle_groups: ['lats','rhomboids','mid_traps','biceps'], variation_level: 2,
    parent_exercise_id: EX.dbRow, is_bodyweight: false,
    default_rep_min: 10, default_rep_max: 12, default_rest_sec: 90, is_compound: true,
    notes: 'Chest against pad. Full stretch forward, full contraction back. 2RIR final set.' },

  // === ISOLATION — ARMS ===
  { id: EX.dbBicepCurl, name: 'Dumbbell Bicep Curl', movement_pattern: 'isolation',
    muscle_groups: ['biceps'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 10, default_rep_max: 12, default_rest_sec: 60, is_compound: false,
    notes: 'No momentum. Full supination at top. Full stretch at bottom. Take last set to failure.' },
  { id: EX.barbellCurl, name: 'Barbell Curl', movement_pattern: 'isolation',
    muscle_groups: ['biceps'], variation_level: 2,
    parent_exercise_id: EX.dbBicepCurl, is_bodyweight: false,
    default_rep_min: 8, default_rep_max: 10, default_rest_sec: 60, is_compound: false,
    notes: 'No momentum. Keep elbows pinned. Last set to failure.' },
  { id: EX.hammerCurl, name: 'Hammer Curl', movement_pattern: 'isolation',
    muscle_groups: ['biceps','brachialis','forearms'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 10, default_rep_max: 12, default_rest_sec: 60, is_compound: false,
    notes: 'Neutral grip (thumbs up). Great for brachialis and forearm development.' },
  { id: EX.overheadTricepExt, name: 'Overhead Tricep Extension', movement_pattern: 'isolation',
    muscle_groups: ['triceps'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 10, default_rep_max: 15, default_rest_sec: 60, is_compound: false,
    notes: 'Arms overhead loads the long head. Full stretch above head. Last set to failure.' },
  { id: EX.tricepPushdown, name: 'Tricep Pushdown', movement_pattern: 'isolation',
    muscle_groups: ['triceps'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 12, default_rep_max: 15, default_rest_sec: 60, is_compound: false,
    notes: 'Elbows stay at sides. Full extension at bottom. Squeeze. Last set to failure.' },

  // === ISOLATION — SHOULDERS ===
  { id: EX.dbLateralRaise, name: 'Dumbbell Lateral Raise', movement_pattern: 'isolation',
    muscle_groups: ['lateral_deltoid'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 15, default_rep_max: 20, default_rest_sec: 60, is_compound: false,
    notes: 'Slight lean forward. Lead with elbows. Use LIGHT weight. Take last set to failure.' },
  { id: EX.cableLateralRaise, name: 'Cable Lateral Raise', movement_pattern: 'isolation',
    muscle_groups: ['lateral_deltoid'], variation_level: 2,
    parent_exercise_id: EX.dbLateralRaise, is_bodyweight: false,
    default_rep_min: 15, default_rep_max: 20, default_rest_sec: 60, is_compound: false,
    notes: 'Cable provides constant tension. Cross-body cable for full ROM.' },
  { id: EX.facePull, name: 'Face Pull', movement_pattern: 'isolation',
    muscle_groups: ['rear_deltoid','mid_traps','rhomboids'], variation_level: 2,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 15, default_rep_max: 20, default_rest_sec: 60, is_compound: false,
    notes: 'Pull to face, elbows high. External rotate at top. Crucial for shoulder health.' },

  // === CORE ===
  { id: EX.plank, name: 'Plank', movement_pattern: 'core',
    muscle_groups: ['core','spinal_erectors'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: true,
    default_rep_min: 30, default_rep_max: 60, default_rest_sec: 60, is_compound: false,
    notes: 'Time-based in seconds. Neutral spine. Squeeze glutes and abs. Breathe.' },
  { id: EX.deadBug, name: 'Dead Bug', movement_pattern: 'core',
    muscle_groups: ['core','hip_flexors'], variation_level: 1,
    parent_exercise_id: null, is_bodyweight: true,
    default_rep_min: 8, default_rep_max: 12, default_rest_sec: 60, is_compound: false,
    notes: 'Keep low back pressed to floor throughout. Slow controlled limb extension.' },
  { id: EX.farmersWalk, name: "Farmer's Walk", movement_pattern: 'core',
    muscle_groups: ['core','traps','forearms','glutes'], variation_level: 2,
    parent_exercise_id: null, is_bodyweight: false,
    default_rep_min: 20, default_rep_max: 40, default_rest_sec: 90, is_compound: true,
    notes: 'Distance or time based. Heavy dumbbells. Tall posture. No swaying.' },
  { id: EX.abWheelRollout, name: 'Ab Wheel Rollout', movement_pattern: 'core',
    muscle_groups: ['core','lats'], variation_level: 2,
    parent_exercise_id: null, is_bodyweight: true,
    default_rep_min: 6, default_rep_max: 10, default_rest_sec: 90, is_compound: false,
    notes: 'From knees. Keep hips down. Brace abs hard. Stop before hips sag.' },
];

// User ID
const USER_ID = 'user-001';

// Template IDs
const TMPL_A = 'tmpl-a-001';
const TMPL_B = 'tmpl-b-001';

const defaultUser = {
  id: USER_ID,
  name: 'Faraz',
  height_cm: 188,
  dob: '2006-01-01',
  goal_rate_kg_week: 0.5,
  protein_target_g: 150,
  base_diet_protein_g: 60,
  created_at: Date.now(),
};

const defaultFoodItems = [
  { id: 'food-001', user_id: USER_ID, name: 'Full-fat milk', serving_unit: '250 ml',
    calories_per_serving: 150, protein_g: 8, carbs_g: 12, fat_g: 8, is_active: true },
  { id: 'food-002', user_id: USER_ID, name: 'Whey protein (milk)', serving_unit: '1 scoop in 250 ml milk',
    calories_per_serving: 300, protein_g: 33, carbs_g: 15, fat_g: 8, is_active: true },
  { id: 'food-003', user_id: USER_ID, name: 'Banana', serving_unit: '1 medium',
    calories_per_serving: 105, protein_g: 1.3, carbs_g: 27, fat_g: 0.4, is_active: true },
  { id: 'food-004', user_id: USER_ID, name: 'Greek yogurt', serving_unit: '150 g',
    calories_per_serving: 150, protein_g: 15, carbs_g: 8, fat_g: 5, is_active: true },
  { id: 'food-005', user_id: USER_ID, name: 'Peanut butter', serving_unit: '1 tbsp (16 g)',
    calories_per_serving: 95, protein_g: 4, carbs_g: 3, fat_g: 8, is_active: true },
  { id: 'food-006', user_id: USER_ID, name: 'Creatine monohydrate', serving_unit: '5 g',
    calories_per_serving: 0, protein_g: 0, carbs_g: 0, fat_g: 0, is_active: false },
  { id: 'food-007', user_id: USER_ID, name: 'Eggs (boiled)', serving_unit: '2 eggs',
    calories_per_serving: 140, protein_g: 12, carbs_g: 1, fat_g: 10, is_active: true },
];

const templateA = {
  id: TMPL_A, user_id: USER_ID, name: 'Full Body A',
  day_index: [0, 2, 4], // Mon, Wed, Fri
  is_active: true, created_at: Date.now(),
};

const templateB = {
  id: TMPL_B, user_id: USER_ID, name: 'Full Body B',
  day_index: [1, 3, 5], // Tue, Thu, Sat
  is_active: true, created_at: Date.now(),
};

const templateExercisesA = [
  { id: 'te-a-001', template_id: TMPL_A, exercise_id: EX.gobletSquat,
    order_index: 0, planned_sets: 2, planned_reps_min: 8, planned_reps_max: 12,
    planned_weight_kg: 16, rest_sec: 120, superset_with_id: null },
  { id: 'te-a-002', template_id: TMPL_A, exercise_id: EX.pushUp,
    order_index: 1, planned_sets: 2, planned_reps_min: 8, planned_reps_max: 20,
    planned_weight_kg: 0, rest_sec: 90, superset_with_id: null },
  { id: 'te-a-003', template_id: TMPL_A, exercise_id: EX.dbRdl,
    order_index: 2, planned_sets: 2, planned_reps_min: 8, planned_reps_max: 10,
    planned_weight_kg: 12, rest_sec: 120, superset_with_id: null },
  { id: 'te-a-004', template_id: TMPL_A, exercise_id: EX.latPulldown,
    order_index: 3, planned_sets: 2, planned_reps_min: 10, planned_reps_max: 12,
    planned_weight_kg: 30, rest_sec: 90, superset_with_id: null },
  { id: 'te-a-005', template_id: TMPL_A, exercise_id: EX.dbBicepCurl,
    order_index: 4, planned_sets: 2, planned_reps_min: 10, planned_reps_max: 12,
    planned_weight_kg: 8, rest_sec: 60, superset_with_id: null },
  { id: 'te-a-006', template_id: TMPL_A, exercise_id: EX.dbLateralRaise,
    order_index: 5, planned_sets: 2, planned_reps_min: 15, planned_reps_max: 20,
    planned_weight_kg: 5, rest_sec: 60, superset_with_id: null },
  { id: 'te-a-007', template_id: TMPL_A, exercise_id: EX.plank,
    order_index: 6, planned_sets: 2, planned_reps_min: 30, planned_reps_max: 60,
    planned_weight_kg: 0, rest_sec: 60, superset_with_id: null },
];

const templateExercisesB = [
  { id: 'te-b-001', template_id: TMPL_B, exercise_id: EX.bulgarianSplitSquat,
    order_index: 0, planned_sets: 2, planned_reps_min: 8, planned_reps_max: 10,
    planned_weight_kg: 10, rest_sec: 120, superset_with_id: null },
  { id: 'te-b-002', template_id: TMPL_B, exercise_id: EX.overheadDbPress,
    order_index: 1, planned_sets: 2, planned_reps_min: 8, planned_reps_max: 12,
    planned_weight_kg: 12, rest_sec: 120, superset_with_id: null },
  { id: 'te-b-003', template_id: TMPL_B, exercise_id: EX.dbRdl,
    order_index: 2, planned_sets: 2, planned_reps_min: 8, planned_reps_max: 10,
    planned_weight_kg: 12, rest_sec: 120, superset_with_id: null },
  { id: 'te-b-004', template_id: TMPL_B, exercise_id: EX.dbRow,
    order_index: 3, planned_sets: 2, planned_reps_min: 10, planned_reps_max: 12,
    planned_weight_kg: 14, rest_sec: 90, superset_with_id: null },
  { id: 'te-b-005', template_id: TMPL_B, exercise_id: EX.hammerCurl,
    order_index: 4, planned_sets: 2, planned_reps_min: 10, planned_reps_max: 12,
    planned_weight_kg: 8, rest_sec: 60, superset_with_id: null },
  { id: 'te-b-006', template_id: TMPL_B, exercise_id: EX.overheadTricepExt,
    order_index: 5, planned_sets: 2, planned_reps_min: 10, planned_reps_max: 15,
    planned_weight_kg: 10, rest_sec: 60, superset_with_id: null },
  { id: 'te-b-007', template_id: TMPL_B, exercise_id: EX.deadBug,
    order_index: 6, planned_sets: 2, planned_reps_min: 8, planned_reps_max: 12,
    planned_weight_kg: 0, rest_sec: 60, superset_with_id: null },
];

export async function seedDatabase() {
  const existingUser = await db.users.get(USER_ID);
  if (existingUser) return; // Already seeded

  await db.transaction('rw',
    db.users, db.exercises, db.workout_templates,
    db.template_exercises, db.food_items,
    async () => {
      await db.users.add(defaultUser);
      await db.exercises.bulkAdd(exercises);
      await db.workout_templates.bulkAdd([templateA, templateB]);
      await db.template_exercises.bulkAdd([...templateExercisesA, ...templateExercisesB]);
      await db.food_items.bulkAdd(defaultFoodItems);
    }
  );
}

export { USER_ID, EX };
